# Generated by Django 5.0.2 on 2024-03-08 20:58

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Сообщение о критической ошибке'), ('B', 'Сообщение, требующее внимания'), ('C', 'Предложения по работе проекта'), ('D', 'Информационное сообщение')], max_length=1, verbose_name='Статус сообщения')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, max_length=1000, verbose_name='Свободный комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Все сообщения',
                'ordering': ['-time_create', 'status', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=1000, verbose_name='Свободный комментарий')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор ответа')),
                ('post', models.ForeignKey(default=blog.models.Answer.answer_default, on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='К сообщению')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы на сообщения разработки',
                'ordering': ['-time_create', 'post'],
            },
        ),
    ]
