# Generated by Django 5.0.2 on 2024-02-25 21:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('units', models.CharField(blank=True, max_length=25, null=True, verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Реагент',
                'verbose_name_plural': 'Реагенты',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('1', 'Уборка ручным водным пылесосом'), ('2', 'Чистка ватерлинии'), ('3', 'Уборка роботом-пылесосом'), ('4', 'Промывка фильтра'), ('5', 'Чистка стен щеткой'), ('6', 'Долив свежей воды')], max_length=50)),
            ],
            options={
                'verbose_name': 'Сервисная операция',
                'verbose_name_plural': 'Сервисные работы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Телефон')),
                ('place', models.TextField(blank=True, max_length=255, verbose_name='Место расположения')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='Объём')),
                ('year_create', models.CharField(blank=True, max_length=4, verbose_name='Год постройки')),
                ('equipment', models.TextField(blank=True, max_length=1000, verbose_name='Комплектация')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бассейн',
                'verbose_name_plural': 'Бассейны',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PoolService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('PH', models.FloatField(blank=True, max_length=3, null=True, verbose_name='Ph')),
                ('RX', models.IntegerField(blank=True, null=True, verbose_name='Rx')),
                ('CL', models.FloatField(blank=True, max_length=3, null=True, verbose_name='Cl')),
                ('T', models.FloatField(blank=True, max_length=4, null=True, verbose_name='Т°C')),
                ('water_cond', models.CharField(blank=True, max_length=50, verbose_name='Состояние воды')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='Свободный комментарий')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('pool', models.ManyToManyField(blank=True, to='poolservice.pool', verbose_name='Бассейн')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('reagents', models.ManyToManyField(blank=True, to='poolservice.reagent', verbose_name='Добавленные реагенты')),
            ],
            options={
                'verbose_name': 'Сервисный выезд',
                'verbose_name_plural': 'Журнал сервисных операций',
                'ordering': ['date_create', 'title'],
            },
        ),
    ]
