# Generated by Django 5.0.2 on 2024-02-26 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolservice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poolservice',
            name='reagents',
        ),
        migrations.DeleteModel(
            name='ServiceWork',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='user',
        ),
        migrations.RemoveField(
            model_name='poolservice',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='poolservice',
            name='user',
        ),
        migrations.AddField(
            model_name='poolservice',
            name='serviceworks',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Выполненные работы'),
        ),
        migrations.RemoveField(
            model_name='poolservice',
            name='pool',
        ),
        migrations.DeleteModel(
            name='Reagent',
        ),
        migrations.AddField(
            model_name='poolservice',
            name='reagents',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Добавленные реагенты'),
        ),
        migrations.AddField(
            model_name='poolservice',
            name='pool',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='poolservice.pool'),
            preserve_default=False,
        ),
    ]
