# Generated by Django 5.0.2 on 2024-02-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolservice', '0002_remove_poolservice_reagents_delete_servicework_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='year_create',
            field=models.CharField(blank=True, max_length=10, verbose_name='Год постройки'),
        ),
    ]
