# Generated by Django 5.0.2 on 2024-02-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolservice', '0004_rename_serviceworks_poolservice_works_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poolservice',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Сервисный выезд', 'verbose_name_plural': 'Журнал сервисных операций'},
        ),
        migrations.RemoveField(
            model_name='poolservice',
            name='date_create',
        ),
        migrations.AddField(
            model_name='poolservice',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-23 12:35', verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poolservice',
            name='reagents',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Добавленные реагенты'),
        ),
        migrations.AlterField(
            model_name='poolservice',
            name='works',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Выполненные работы'),
        ),
    ]
