# Generated by Django 5.0.2 on 2024-02-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolservice', '0005_alter_poolservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='owner',
            field=models.CharField(default='', max_length=255, verbose_name='Владелец,Пользователь'),
            preserve_default=False,
        ),
    ]
