# Generated by Django 5.0.2 on 2024-03-13 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolservice', '0009_alter_pool_owner_alter_poolservice_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poolservice',
            name='CL',
            field=models.FloatField(blank=True, max_length=4, null=True, verbose_name='Cl'),
        ),
        migrations.AlterField(
            model_name='poolservice',
            name='PH',
            field=models.FloatField(blank=True, max_length=4, null=True, verbose_name='Ph'),
        ),
        migrations.AlterField(
            model_name='poolservice',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='poolservice',
            name='pool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='poolservice.pool', verbose_name='Бассейн'),
        ),
    ]
