# Generated by Django 5.0.2 on 2024-03-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolservice', '0010_pool_author_alter_poolservice_cl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Сервисная операция',
                'verbose_name_plural': 'Сервисные работы',
                'ordering': ['title'],
            },
        ),
    ]
