# Generated by Django 5.0.2 on 2024-03-14 22:15

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolservice', '0011_servicework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolservice',
            name='works',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Уборка бассейна ручным водным пылесосом', 'Уборка бассейна ручным водным пылесосом'), ('Промывка фильтра', 'Промывка фильтра'), ('Уборка бассейна роботом-пылесосом', 'Уборка бассейна роботом-пылесосом'), ('Чистка стен щёткой', 'Чистка стен щёткой'), ('Долив свежей воды', 'Долив свежей воды'), ('Чистка ватерлинии', 'Чистка ватерлинии')], max_length=1000, verbose_name='Выполненные работы'),
        ),
    ]
